# Generated by Django 4.1.3 on 2022-11-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('boat', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('handicap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ongoing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SailingRaceManager.series')),
            ],
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_handicap', models.IntegerField(null=True)),
                ('time', models.DurationField(null=True)),
                ('shore_officer', models.BooleanField(default=False)),
                ('did_not_finnish', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('boat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SailingRaceManager.handicap')),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_id_set', to='SailingRaceManager.sailor')),
                ('sailor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sailor_id_set', to='SailingRaceManager.sailor')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('completed', models.BooleanField()),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SailingRaceManager.series')),
            ],
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('sailor_id', 'race_id'), name='unique_entry'),
        ),
    ]
